name: Workflow
on:
  push:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install dependencies ğŸ–¥ï¸
        run: yarn install

      - name: Run unit test's ğŸª²
        run: yarn run test
  e2e:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install dependencies ğŸ–¥ï¸
        run: yarn install

      - name: Run E2E test's ğŸ–¥ï¸
        run: npm run e2e

  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    env:
      CI: true
      REACT_APP_API_URI: ${{ secrets.REACT_APP_API_URI }}
      REACT_APP_API_TOKEN: ${{ secrets.REACT_APP_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install dependencies
        run: yarn install

      - name: Create e2e reporter ğŸ–¥ï¸
        run: npm run e2e

      - uses: actions/upload-artifact@v2
        if: ${{ github.ref != 'refs/heads/master' }}
        with:
          name: test-artifacts
          path: public/e2e-reporter/

      - name: Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: yarn run predeploy

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
          clean: true
